CREATE DATABASE tourism_php;

CREATE TABLE info 
(
    id INT,
    url_key VARCHAR(255) NOT NULL,
    content1 TEXT CHARACTER SET utf8 DEFAULT NULL,
    content2 TEXT DEFAULT NULL,
    content3 TEXT DEFAULT NULL,
    content4 TEXT DEFAULT NULL,
    content5 TEXT DEFAULT NULL,
    content6 TEXT DEFAULT NULL,
    UNIQUE KEY url_key (url_key)
);


INSERT INTO info (url_key, content1) VALUES ('gruziya','Мы встретим вас в аэропорту и доставим в гостиницу. После небольшого отдыха вас ждет экскурсия по Тбилиси. Наш
                    тур начнется с кафедрального собора святой Троицы . Во время короткого тура вы узнаете историю Тбилиси в
                    Абанотубане, сделаете несколько фото у водопада Легвтахеви,прокатитесь на канатке с парка Рике до крепости
                    Нарикала, увидите представление “Цикл Жизни” на часовой башне у театра Габриадзе.');
INSERT INTO info (url_key, content1, content2, content3, content4, content5) VALUES ('about_el','Elephants are the largest existing land animals. Three living species are currently recognised: the African bush elephant, the African forest elephant, and the Asian elephant. They are an informal grouping within the proboscidean family Elephantidae. Elephantidae is the only surviving family of proboscideans; extinct members include the mastodons. Elephantidae also contains several extinct groups, including the mammoths and straight-tusked elephants. African elephants have larger ears and concave backs, whereas Asian elephants have smaller ears, and convex or level backs. The distinctive features of all elephants include a long proboscis called a trunk, tusks, large ear flaps, massive legs, and tough but sensitive skin. The trunk is used for breathing, bringing food and water to the mouth, and grasping objects. Tusks, which are derived from the incisor teeth, serve both as weapons and as tools for moving objects and digging. The large ear flaps assist in maintaining a constant body temperature as well as in communication. The pillar-like legs carry their great weight.',
                                                                            'Elephants are scattered throughout sub-Saharan Africa, South Asia, and Southeast Asia and are found in different habitats, including savannahs, forests, deserts, and marshes. They are herbivorous, and they stay near water when it is accessible. They are considered to be keystone species, due to their impact on their environments. Elephants have a fission-fusion society, in which multiple family groups come together to socialise. Females (cows) tend to live in family groups, which can consist of one female with her calves or several related females with offspring. The groups, which do not include bulls, are usually led by the oldest cow, known as the matriarch.',
                                                                            'Males (bulls) leave their family groups when they reach puberty and may live alone or with other males. Adult bulls mostly interact with family groups when looking for a mate. They enter a state of increased testosterone and aggression known as musth, which helps them gain dominance over other males as well as reproductive success. Calves are the centre of attention in their family groups and rely on their mothers for as long as three years. Elephants can live up to 70 years in the wild. They communicate by touch, sight, smell, and sound; elephants use infrasound, and seismic communication over long distances. Elephant intelligence has been compared with that of primates and cetaceans. They appear to have self-awareness, and appear to show empathy for dying and dead family members.',
                                                                            'African bush elephants and Asian elephants are listed as endangered and African forest elephants as critically endangered by the International Union for Conservation of Nature (IUCN). One of the biggest threats to elephant populations is the ivory trade, as the animals are poached for their ivory tusks. Other threats to wild elephants include habitat destruction and conflicts with local people. Elephants are used as working animals in Asia. In the past, they were used in war; today, they are often controversially put on display in zoos, or exploited for entertainment in circuses. Elephants are highly recognisable and have been featured in art, folklore, religion, literature, and popular culture.',
                                                                            'African bush elephants are the largest species, with males being 304-336 cm (10 ft 0 in - 11 ft 0 in) tall at the shoulder with a body mass of 5.2-6.9 t (5.7-7.6 short tons) and females standing 247-273 cm (8 ft 1 in - 8 ft 11 in) tall at the shoulder with a body mass of 2.6-3.5 t (2.9-3.9 short tons). Male Asian elephants are usually about 261-289 cm (8 ft 7 in - 9 ft 6 in) tall at the shoulder and 3.5-4.6 t (3.9-5.1 short tons) whereas females are 228-252 cm (7 ft 6 in - 8 ft 3 in) tall at the shoulder and 2.3-3.1 t (2.5-3.4 short tons). African forest elephants are the smallest species, with males usually being around 209-231 cm (6 ft 10 in - 7 ft 7 in) tall at the shoulder and 1.7-2.3 t (1.9-2.5 short tons). Male African bush elephants are typically 23% taller than females, whereas male Asian elephants are only around 15% taller than females.'); 
INSERT INTO info (url_key, content1, content2, content3, content4, content5, content6) VALUES ('about_rhin','A rhinoceros  commonly abbreviated to rhino, is a member of any of the five extant species (or numerous extinct species) of odd-toed ungulates in the family Rhinocerotidae. (It can also refer to a member of any of the extinct species of the superfamily Rhinocerotoidea.) Two of the extant species are native to Africa, and three to South and Southeast Asia.',
                                                                                                'Rhinoceroses are some of the largest remaining megafauna: all weigh at least one tonne in adulthood. They have a herbivorous diet, small brains (400-600 g) for mammals of their size, one or two horns, and a thick (1.5-5 cm), protective skin formed from layers of collagen positioned in a lattice structure. They generally eat leafy material, although their ability to ferment food in their hindgut allows them to subsist on more fibrous plant matter when necessary. Unlike other perissodactyls, the two African species of rhinoceros lack teeth at the front of their mouths; they rely instead on their lips to pluck food.',
                                                                                                'Rhinoceros are killed by poachers for their horns, which are bought and sold on the black market for high prices, leading to most living rhinoceros species being considered endangered. The contemporary market for rhino horn is overwhelmingly driven by China and Vietnam, where it is bought by wealthy consumers to use in traditional Chinese medicine, among other uses. Rhino horns are made of keratin, the same material as hair and fingernails, and there is no good evidence of any health benefits.A market also exists for rhino horn dagger handles in Yemen, which was the major source of demand for rhino horn in the 1970s and 1980s.',
                                                                                                'The family Rhinocerotidae consists of only four extant genera: Ceratotherium (white rhinoceros), Diceros (black rhinoceros), Dicerorhinus (Sumatran rhinoceros), and Rhinoceros (Indian and Javan rhinoceros). The living species fall into three categories. The two African species, the white rhinoceros and the black rhinoceros, belong to the tribe Dicerotini, which originated in the middle Miocene, about 14.2 million years ago.Rhinocerotoids diverged from other perissodactyls by the early Eocene. Fossils of Hyrachyus eximus found in North America date to this period. This small hornless ancestor resembled a tapir or small horse more than a rhino. Three families, sometimes grouped together as the superfamily Rhinocerotoidea, evolved in the late Eocene, namely the Hyracodontidae, Amynodontidae and Rhinocerotidae.',
                                                                                                'There are two subspecies of white rhinoceros: the southern white rhinoceros (Ceratotherium simum simum) and the northern white rhinoceros (Ceratotherium simum cottoni). As of 2013, the southern subspecies has a wild population of 20,405-making them the most abundant rhino subspecies in the world. However, the northern subspecies is critically endangered, with all that is known to remain being two captive females. There is no conclusive explanation of the name "white rhinoceros". A popular idea that "white" is a distortion of either the Afrikaans word wyd or the Dutch word wijd (or its other possible spellings whyde, weit, etc.,), meaning "wide" and referring to the rhino''s square lips, is not supported by linguistic studies.',
                                                                                                'The white rhino has an immense body and large head, a short neck and broad chest. Females weigh 1,600 kg (4,000 lb) and males 2,400 kg (5,000 lb). The head-and-body length is 3.5-4.6 m (11-15 ft) and the shoulder height is 1.8-2 m (5.9-6.6 ft). On its snout it has two horns. The front horn is larger than the other horn and averages 90 cm (35 in) in length and can reach 150 cm (59 in). The white rhinoceros also has a prominent muscular hump that supports its relatively large head. The colour of this animal can range from yellowish brown to slate grey. Most of its body hair is found on the ear fringes and tail bristles, with the rest distributed rather sparsely over the rest of the body. White rhinos have the distinctive flat broad mouth that is used for grazing.');